// matching
export const APP_MATCHING_ROWS_RESET = "APP_MATCHING_ROWS_RESET"
export const APP_MATCHING_ROWS_REQUEST = "APP_MATCHING_ROWS_REQUEST"
export const APP_MATCHING_ROWS_SUCCESS = "APP_MATCHING_ROWS_SUCCESS"
export const APP_MATCHING_ROWS_FAILURE = "APP_MATCHING_ROWS_FAILURE"
export const APP_MATCHING_ROWS_INVALIDATE = "APP_MATCHING_ROWS_INVALIDATE"
export const APP_MATCHING_ROWS_REMOVE = "APP_MATCHING_ROWS_REMOVE"
export const APP_MATCHING_ROWS_FILTERS_RECEIVE = "APP_MATCHING_ROWS_FILTERS_RECEIVE"
export const APP_MATCHING_ROWS_TOTAL_RECEIVE = "APP_MATCHING_ROWS_TOTAL_RECEIVE"

// manufacturers
export const APP_MATCHING_LIST_MANUFACTURERS_RESET = "APP_MATCHING_LIST_MANUFACTURERS_RESET"
export const APP_MATCHING_LIST_MANUFACTURERS_REQUEST = "APP_MATCHING_LIST_MANUFACTURERS_REQUEST"
export const APP_MATCHING_LIST_MANUFACTURERS_SUCCESS = "APP_MATCHING_LIST_MANUFACTURERS_SUCCESS"
export const APP_MATCHING_LIST_MANUFACTURERS_FAILURE = "APP_MATCHING_LIST_MANUFACTURERS_FAILURE"
export const APP_MATCHING_LIST_MANUFACTURERS_INVALIDATE = "APP_MATCHING_LIST_MANUFACTURERS_INVALIDATE"
export const APP_MATCHING_LIST_MANUFACTURERS_REMOVE = "APP_MATCHING_LIST_MANUFACTURERS_REMOVE"

// retailers
export const APP_MATCHING_LIST_RETAILERS_RESET = "APP_MATCHING_LIST_RETAILERS_RESET"
export const APP_MATCHING_LIST_RETAILERS_REQUEST = "APP_MATCHING_LIST_RETAILERS_REQUEST"
export const APP_MATCHING_LIST_RETAILERS_SUCCESS = "APP_MATCHING_LIST_RETAILERS_SUCCESS"
export const APP_MATCHING_LIST_RETAILERS_FAILURE = "APP_MATCHING_LIST_RETAILERS_FAILURE"
export const APP_MATCHING_LIST_RETAILERS_INVALIDATE = "APP_MATCHING_LIST_RETAILERS_INVALIDATE"
export const APP_MATCHING_LIST_RETAILERS_REMOVE = "APP_MATCHING_LIST_RETAILERS_REMOVE"

// trade items
export const APP_MATCHING_MATCH_TRADE_ITEMS_LIST_RESET = "APP_MATCHING_MATCH_TRADE_ITEMS_LIST_RESET"
export const APP_MATCHING_MATCH_TRADE_ITEMS_LIST_REQUEST = "APP_MATCHING_MATCH_TRADE_ITEMS_LIST_REQUEST"
export const APP_MATCHING_MATCH_TRADE_ITEMS_LIST_SUCCESS = "APP_MATCHING_MATCH_TRADE_ITEMS_LIST_SUCCESS"
export const APP_MATCHING_MATCH_TRADE_ITEMS_LIST_FAILURE = "APP_MATCHING_MATCH_TRADE_ITEMS_LIST_FAILURE"
export const APP_MATCHING_MATCH_TRADE_ITEMS_LIST_INVALIDATE = "APP_MATCHING_MATCH_TRADE_ITEMS_LIST_INVALIDATE"
export const APP_MATCHING_MATCH_TRADE_ITEMS_LIST_REMOVE = "APP_MATCHING_MATCH_TRADE_ITEMS_LIST_REMOVE"
export const APP_MATCHING_MATCH_RECEIVE = "APP_MATCHING_MATCH_RECEIVE"
export const APP_MATCHING_MATCH_FILTERS_RECEIVE = "APP_MATCHING_MATCH_FILTERS_RECEIVE"
export const APP_MATCHING_MATCH_TRADE_ITEM_RECEIVE = "APP_MATCHING_MATCH_TRADE_ITEM_RECEIVE"
export const APP_MATCHING_MATCH_IS_CREATING_NEW_RECEIVE = "APP_MATCHING_MATCH_IS_CREATING_NEW_RECEIVE"
