export const PUBLIC_URL = process.env.PUBLIC_URL;
export const DOMAIN = process.env.REACT_APP_CDM_DOMAIN;
export const CMS_V2_DOMAIN = process.env.REACT_APP_CDM_CMS_V2_DOMAIN;
export const ENV = process.env.NODE_ENV;

// services
//
export const CDM_TRADE_ITEM_INDEXER_URI =
  process.env.REACT_APP_CDM_TRADE_ITEM_INDEXER_URI;
export const CDM_TRADE_ITEM_STORAGE_URI =
  process.env.REACT_APP_CDM_TRADE_ITEM_STORAGE_URI;
export const CDM_TRADE_ITEM_MANAGEMENT_URI =
  process.env.REACT_APP_CDM_TRADE_ITEM_MANAGEMENT_URI;
export const CDM_AUTH_URI = process.env.REACT_APP_CDM_AUTH_URI;
export const CDM_TRADE_ITEM_PROPERTIES_URI =
  process.env.REACT_APP_CDM_TRADE_ITEM_PROPERTIES_URI;
export const CDM_MANUFACTURER_MANAGEMENT_URI =
  process.env.REACT_APP_CDM_MANUFACTURER_MANAGEMENT_URI;
export const CDM_TARGET_MARKET_URI =
  process.env.REACT_APP_CDM_TARGET_MARKET_URI;
export const CDM_MATRIX_MAPPING_URI =
  process.env.REACT_APP_CDM_MATRIX_MAPPING_URI;
export const CDM_MATRIX_VALIDATION_URI =
  process.env.REACT_APP_CDM_MATRIX_VALIDATION_URI;
export const CDM_BUSINESS_RULES_MGMNT =
  process.env.REACT_APP_CDM_BUSINESS_RULES_MGMNT_URI;
export const CDM_BUSINESS_RULES_EVAL =
  process.env.REACT_APP_CDM_BUSINESS_RULES_EVAL_URI;
export const CDM_IMPORT_SERVICE_URI =
  process.env.REACT_APP_CDM_IMPORT_SERVICE_URI;
export const CDM_RETAILER_MGMNT_SERVICE_URI =
  process.env.REACT_APP_CDM_RETAILER_MGMNT_SERVICE_URI;
export const CDM_ENRICHMENT_SERVICE_URI =
  process.env.REACT_APP_CDM_ENRICHMENT_SERVICE_URI;
export const CDM_USER_MANAGEMENT_URI =
  process.env.REACT_APP_CDM_USER_MANAGEMENT_URI;
export const CDM_TRIGGER_MANAGEMENT_SERVICE_URI =
  process.env.REACT_APP_CDM_TRIGGER_MANAGEMENT_SERVICE_URI;
export const CDM_FORMAT_MANAGEMENT_SERVICE_URI =
  process.env.REACT_APP_CDM_FORMAT_MANAGEMENT_SERVICE_URI;
export const CDM_FORMAT_PROCESSING_SERVICE_URI =
  process.env.REACT_APP_CDM_FORMAT_PROCESSING_SERVICE_URI;
export const CDM_TRANSFORMATION_MANAGEMENT_SERVICE_URI =
  process.env.REACT_APP_CDM_TRANSFORMATION_MANAGEMENT_SERVICE_URI;
export const CDM_TRANSFORMATION_PROCESSING_SERVICE_URI =
  process.env.REACT_APP_CDM_TRANSFORMATION_PROCESSING_SERVICE_URI;
export const CDM_ACKNOWLEDGEMENT_SERVICE_URI =
  process.env.REACT_APP_CDM_ACKNOWLEDGEMENT_SERVICE_URI;
export const CDM_TRANSPORT_MANAGEMENT_SERVICE_URI =
  process.env.REACT_APP_CDM_TRANSPORT_MANAGEMENT_SERVICE_URI;
export const CDM_PRE_COMPUTING_SERVICE_URI =
  process.env.REACT_APP_CDM_PRE_COMPUTING_SERVICE_URI;
export const CDM_IMPORT_RESOURCE_SERVICE_URI =
  process.env.REACT_APP_CDM_IMPORT_RESOURCE_SERVICE_URI;
export const CDM_SUBSCRIPTION_SERVICE_URI =
  process.env.REACT_APP_CDM_SUBSCRIPTION_SERVICE_URI;
export const CDM_ENRICHMENT_REQUEST_SERVICE_URI =
  process.env.REACT_APP_CDM_ENRICHMENT_REQUEST_SERVICE_URI;
export const CDM_COLLECTION_SERVICE_URI =
  process.env.REACT_APP_CDM_COLLECTION_SERVICE_URI;
export const CDM_MESSAGING_SERVICE_URI =
  process.env.REACT_APP_CDM_MESSAGING_SERVICE_URI;

// auth
//
export const CDM_AUTH_CLIENT_ID = process.env.REACT_APP_CDM_AUTH_CLIENT_ID;
export const CDM_AUTH_CLIENT_SECRET =
  process.env.REACT_APP_CDM_AUTH_CLIENT_SECRET;
export const CDM_AUTH_GRANT_TYPE = process.env.REACT_APP_CDM_AUTH_GRANT_TYPE;

// lang
//
export const CDM_AVAILABLE_LANG = ["fr-FR", "it-IT", "en-GB", "de-DE", "es-ES"];
export const CDM_DEFAULT_LANG = "fr-FR";

// release notes
//
export const CDM_RELEASE_NOTES_URL =
  "https://storage.gra.cloud.ovh.net/v1/AUTH_8f75d74f077b4b88b4aa7227d4ee5f6f/documentation/release_notes.json";
