import { combineReducers } from 'redux'
import createList from "../common/reducers/createList"
import createResource from "../common/reducers/createResource"
import * as types from './types'

// Actions
//
const rulesList = createList({
  RESET: types.APP_BUSINESS_RULES_LIST_RESET,
  REQUEST: types.APP_BUSINESS_RULES_LIST_REQUEST,
  SUCCESS: types.APP_BUSINESS_RULES_LIST_SUCCESS,
  FAILURE: types.APP_BUSINESS_RULES_LIST_FAILURE,
  INVALIDATE: types.APP_BUSINESS_RULES_LIST_INVALIDATE,
  REMOVE: types.APP_BUSINESS_RULES_LIST_REMOVE,
})

const validators = createList({
  RESET: types.APP_BUSINESS_RULES_VALIDATORS_LIST_RESET,
  REQUEST: types.APP_BUSINESS_RULES_VALIDATORS_LIST_REQUEST,
  SUCCESS: types.APP_BUSINESS_RULES_VALIDATORS_LIST_SUCCESS,
  FAILURE: types.APP_BUSINESS_RULES_VALIDATORS_LIST_FAILURE,
  INVALIDATE: types.APP_BUSINESS_RULES_VALIDATORS_LIST_INVALIDATE,
  REMOVE: types.APP_BUSINESS_RULES_VALIDATORS_LIST_REMOVE,
})

const ruleEdit = createResource({
  RESET: types.APP_BUSINESS_RULES_EDIT_RESET,
  SUCCESS: types.APP_BUSINESS_RULES_EDIT_SUCCESS,
})

const listPropertiesActions = {
  RESET: types.APP_BUSINESS_RULES_PROPERTIES_LIST_RESET,
  REQUEST: types.APP_BUSINESS_RULES_PROPERTIES_LIST_REQUEST,
  SUCCESS: types.APP_BUSINESS_RULES_PROPERTIES_LIST_SUCCESS,
  FAILURE: types.APP_BUSINESS_RULES_PROPERTIES_LIST_FAILURE,
  INVALIDATE: types.APP_BUSINESS_RULES_PROPERTIES_LIST_INVALIDATE,
  REMOVE: types.APP_BUSINESS_RULES_PROPERTIES_LIST_REMOVE,
}

const tradeItemCategoriesListActions = {
  RESET: types.APP_BUSINESS_RULES_TRADE_ITEM_CATEGORIES_LIST_RESET,
  REQUEST: types.APP_BUSINESS_RULES_TRADE_ITEM_CATEGORIES_LIST_REQUEST,
  SUCCESS: types.APP_BUSINESS_RULES_TRADE_ITEM_CATEGORIES_LIST_SUCCESS,
  FAILURE: types.APP_BUSINESS_RULES_TRADE_ITEM_CATEGORIES_LIST_FAILURE,
  INVALIDATE: types.APP_BUSINESS_RULES_TRADE_ITEM_CATEGORIES_LIST_INVALIDATE,
  REMOVE: types.APP_BUSINESS_RULES_TRADE_ITEM_CATEGORIES_LIST_REMOVE,
}

const groupsListActions = {
  RESET: types.APP_BUSINESS_RULES_GROUPS_LIST_RESET,
  REQUEST: types.APP_BUSINESS_RULES_GROUPS_LIST_REQUEST,
  SUCCESS: types.APP_BUSINESS_RULES_GROUPS_LIST_SUCCESS,
  FAILURE: types.APP_BUSINESS_RULES_GROUPS_LIST_FAILURE,
  INVALIDATE: types.APP_BUSINESS_RULES_GROUPS_LIST_INVALIDATE,
  REMOVE: types.APP_BUSINESS_RULES_GROUPS_LIST_REMOVE,
}

const taxonomiesListActions = {
  RESET: types.APP_BUSINESS_RULES_TAXONOMIES_LIST_RESET,
  REQUEST: types.APP_BUSINESS_RULES_TAXONOMIES_LIST_REQUEST,
  SUCCESS: types.APP_BUSINESS_RULES_TAXONOMIES_LIST_SUCCESS,
  FAILURE: types.APP_BUSINESS_RULES_TAXONOMIES_LIST_FAILURE,
  INVALIDATE: types.APP_BUSINESS_RULES_TAXONOMIES_LIST_INVALIDATE,
  REMOVE: types.APP_BUSINESS_RULES_TAXONOMIES_LIST_REMOVE,
}

const rulesSetsList = createList({
  RESET: types.APP_BUSINESS_RULES_SET_LIST_RESET,
  REQUEST: types.APP_BUSINESS_RULES_SET_LIST_REQUEST,
  SUCCESS: types.APP_BUSINESS_RULES_SET_LIST_SUCCESS,
  FAILURE: types.APP_BUSINESS_RULES_SET_LIST_FAILURE,
  INVALIDATE: types.APP_BUSINESS_RULES_SET_LIST_INVALIDATE,
  REMOVE: types.APP_BUSINESS_RULES_SET_LIST_REMOVE,
})

const valuesGroups = createList({
  RESET: types.APP_BUSINESS_RULES_VALUES_GROUPS_LIST_RESET,
  REQUEST: types.APP_BUSINESS_RULES_VALUES_GROUPS_LIST_REQUEST,
  SUCCESS: types.APP_BUSINESS_RULES_VALUES_GROUPS_LIST_SUCCESS,
  FAILURE: types.APP_BUSINESS_RULES_VALUES_GROUPS_LIST_FAILURE,
  INVALIDATE: types.APP_BUSINESS_RULES_VALUES_GROUPS_LIST_INVALIDATE,
  REMOVE: types.APP_BUSINESS_RULES_VALUES_GROUPS_LIST_REMOVE,
})

const ruleSetEdit = createResource({
  RESET: types.APP_BUSINESS_RULES_SET_EDIT_RESET,
  SUCCESS: types.APP_BUSINESS_RULES_SET_EDIT_SUCCESS,
})

// Reducers
//
const tradeItemProperties = combineReducers({
  properties: createList(listPropertiesActions),
  groups: createList(groupsListActions),
  taxonomies: createList(taxonomiesListActions),
  tradeItemCategories: createList(tradeItemCategoriesListActions)
})

// Combine reducer to get default reducer
//
export default combineReducers({
  rulesList,
  ruleEdit,
  tradeItemProperties,
  validators,
  rulesSetsList,
  ruleSetEdit,
  valuesGroups,
})
