export const APP_ACK_CONFLICTS_LIST_RESET = "APP_ACK_CONFLICTS_LIST_RESET"
export const APP_ACK_CONFLICTS_LIST_REQUEST = "APP_ACK_CONFLICTS_LIST_REQUEST"
export const APP_ACK_CONFLICTS_LIST_SUCCESS = "APP_ACK_CONFLICTS_LIST_SUCCESS"
export const APP_ACK_CONFLICTS_LIST_FAILURE = "APP_ACK_CONFLICTS_LIST_FAILURE"
export const APP_ACK_CONFLICTS_LIST_INVALIDATE = "APP_ACK_CONFLICTS_LIST_INVALIDATE"
export const APP_ACK_CONFLICTS_LIST_REMOVE = "APP_ACK_CONFLICTS_LIST_REMOVE"
export const APP_ACK_CONFLICTS_LIST_UPDATE = "APP_ACK_CONFLICTS_LIST_UPDATE"

export const APP_ACK_CONFLICTS_TOTAL_RECEIVED = "APP_ACK_CONFLICTS_TOTAL_RECEIVED"

export const APP_ACK_CONFLICTS_FILTERS_RECEIVED = "APP_ACK_CONFLICTS_FILTERS_RECEIVED"
export const APP_ACK_CONFLICTS_FILTERS_VALUE_RECEIVED = "APP_ACK_CONFLICTS_FILTERS_VALUE_RECEIVED"

export const APP_SUBMISSIONS_LIST_RESET = "APP_SUBMISSIONS_LIST_RESET"
export const APP_SUBMISSIONS_LIST_REQUEST = "APP_SUBMISSIONS_LIST_REQUEST"
export const APP_SUBMISSIONS_LIST_SUCCESS = "APP_SUBMISSIONS_LIST_SUCCESS"
export const APP_SUBMISSIONS_LIST_FAILURE = "APP_SUBMISSIONS_LIST_FAILURE"
export const APP_SUBMISSIONS_LIST_INVALIDATE = "APP_SUBMISSIONS_LIST_INVALIDATE"
export const APP_SUBMISSIONS_LIST_REMOVE = "APP_SUBMISSIONS_LIST_REMOVE"
export const APP_SUBMISSIONS_LIST_UPDATE = "APP_SUBMISSIONS_LIST_UPDATE"

export const APP_SUBMISSIONS_TOTAL_RECEIVED = "APP_SUBMISSIONS_TOTAL_RECEIVED"

export const APP_SUBMISSIONS_FILTERS_RECEIVED = "APP_SUBMISSIONS_FILTERS_RECEIVED"
export const APP_SUBMISSIONS_FILTERS_VALUE_RECEIVED = "APP_SUBMISSIONS_FILTERS_VALUE_RECEIVED"