import { combineReducers } from "redux"
import createList from "../common/reducers/createList"
import createResource from "../common/reducers/createResource"
import createReducer from "../common/reducers/createReducer"
import * as types from "./types"

const format = createResource({
  RESET: types.EXPORT_FORMAT_FORMAT_RESET,
  REQUEST: types.EXPORT_FORMAT_FORMAT_REQUEST,
  SUCCESS: types.EXPORT_FORMAT_FORMAT_SUCCESS,
  FAILURE: types.EXPORT_FORMAT_FORMAT_FAILURE,
  INVALIDATE: types.EXPORT_FORMAT_FORMAT_INVALIDATE
})

const formats = createList({
  RESET: types.EXPORT_FORMAT_FORMATS_RESET,
  REQUEST: types.EXPORT_FORMAT_FORMATS_REQUEST,
  SUCCESS: types.EXPORT_FORMAT_FORMATS_SUCCESS,
  FAILURE: types.EXPORT_FORMAT_FORMATS_FAILURE,
  INVALIDATE: types.EXPORT_FORMAT_FORMATS_INVALIDATE,
  REMOVE: types.EXPORT_FORMAT_FORMATS_REMOVE
})

const taxonomies = createList({
  RESET: types.EXPORT_FORMAT_TAXONOMY_RESET,
  REQUEST: types.EXPORT_FORMAT_TAXONOMY_REQUEST,
  SUCCESS: types.EXPORT_FORMAT_TAXONOMY_SUCCESS,
  FAILURE: types.EXPORT_FORMAT_TAXONOMY_FAILURE,
  INVALIDATE: types.EXPORT_FORMAT_TAXONOMY_INVALIDATE,
  REMOVE: types.EXPORT_FORMAT_TAXONOMY_REMOVE
})

const tradeItemCategories = createList({
  RESET: types.EXPORT_FORMAT_TRADE_ITEM_CATEGORY_RESET,
  REQUEST: types.EXPORT_FORMAT_TRADE_ITEM_CATEGORY_REQUEST,
  SUCCESS: types.EXPORT_FORMAT_TRADE_ITEM_CATEGORY_SUCCESS,
  FAILURE: types.EXPORT_FORMAT_TRADE_ITEM_CATEGORY_FAILURE,
  INVALIDATE: types.EXPORT_FORMAT_TRADE_ITEM_CATEGORY_INVALIDATE,
  REMOVE: types.EXPORT_FORMAT_TRADE_ITEM_CATEGORY_REMOVE
})

const businessRules = createList({
  RESET: types.EXPORT_FORMAT_BUSINESS_RULES_RESET,
  REQUEST: types.EXPORT_FORMAT_BUSINESS_RULES_REQUEST,
  SUCCESS: types.EXPORT_FORMAT_BUSINESS_RULES_SUCCESS,
  FAILURE: types.EXPORT_FORMAT_BUSINESS_RULES_FAILURE,
  INVALIDATE: types.EXPORT_FORMAT_BUSINESS_RULES_INVALIDATE,
  REMOVE: types.EXPORT_FORMAT_BUSINESS_RULES_REMOVE
})

const businessRulesets = createList({
  RESET: types.EXPORT_FORMAT_BUSINESS_RULESETS_RESET,
  REQUEST: types.EXPORT_FORMAT_BUSINESS_RULESETS_REQUEST,
  SUCCESS: types.EXPORT_FORMAT_BUSINESS_RULESETS_SUCCESS,
  FAILURE: types.EXPORT_FORMAT_BUSINESS_RULESETS_FAILURE,
  INVALIDATE: types.EXPORT_FORMAT_BUSINESS_RULESETS_INVALIDATE,
  REMOVE: types.EXPORT_FORMAT_BUSINESS_RULESETS_REMOVE
})

const propertyGroups = createList({
  RESET: types.EXPORT_FORMAT_PROPERTY_GROUPS_RESET,
  REQUEST: types.EXPORT_FORMAT_PROPERTY_GROUPS_REQUEST,
  SUCCESS: types.EXPORT_FORMAT_PROPERTY_GROUPS_SUCCESS,
  FAILURE: types.EXPORT_FORMAT_PROPERTY_GROUPS_FAILURE,
  INVALIDATE: types.EXPORT_FORMAT_PROPERTY_GROUPS_INVALIDATE,
  REMOVE: types.EXPORT_FORMAT_PROPERTY_GROUPS_REMOVE
})

const transformationSets = createList({
  RESET: types.EXPORT_FORMAT_TRANSFORMATION_SET_RESET,
  REQUEST: types.EXPORT_FORMAT_TRANSFORMATION_SET_REQUEST,
  SUCCESS: types.EXPORT_FORMAT_TRANSFORMATION_SET_SUCCESS,
  FAILURE: types.EXPORT_FORMAT_TRANSFORMATION_SET_FAILURE,
  INVALIDATE: types.EXPORT_FORMAT_TRANSFORMATION_SET_INVALIDATE,
  REMOVE: types.EXPORT_FORMAT_TRANSFORMATION_SET_REMOVE
})

const tradeItemProperties = createList({
  RESET: types.EXPORT_FORMAT_TRADE_ITEM_PROPERTIES_RESET,
  REQUEST: types.EXPORT_FORMAT_TRADE_ITEM_PROPERTIES_REQUEST,
  SUCCESS: types.EXPORT_FORMAT_TRADE_ITEM_PROPERTIES_SUCCESS,
  FAILURE: types.EXPORT_FORMAT_TRADE_ITEM_PROPERTIES_FAILURE,
  INVALIDATE: types.EXPORT_FORMAT_TRADE_ITEM_PROPERTIES_INVALIDATE,
  REMOVE: types.EXPORT_FORMAT_TRADE_ITEM_PROPERTIES_REMOVE
})

const transformationsProperties = createList({
  RESET: types.EXPORT_FORMAT_TRANSFORMATIONS_PROPERTIES_RESET,
  REQUEST: types.EXPORT_FORMAT_TRANSFORMATIONS_PROPERTIES_REQUEST,
  SUCCESS: types.EXPORT_FORMAT_TRANSFORMATIONS_PROPERTIES_SUCCESS,
  FAILURE: types.EXPORT_FORMAT_TRANSFORMATIONS_PROPERTIES_FAILURE,
  INVALIDATE: types.EXPORT_FORMAT_TRANSFORMATIONS_PROPERTIES_INVALIDATE,
  REMOVE: types.EXPORT_FORMAT_TRANSFORMATIONS_PROPERTIES_REMOVE
})

const templateValidationJSONActions = createList({
  RESET: types.EXPORT_FORMAT_TRANSFORMATION_TEMPLATE_VALIDATION_JSON_EXPORT_ACTION_LIST_RESET,
  REQUEST: types.EXPORT_FORMAT_TRANSFORMATION_TEMPLATE_VALIDATION_JSON_EXPORT_ACTION_LIST_REQUEST,
  SUCCESS: types.EXPORT_FORMAT_TRANSFORMATION_TEMPLATE_VALIDATION_JSON_EXPORT_ACTION_LIST_SUCCESS,
  FAILURE: types.EXPORT_FORMAT_TRANSFORMATION_TEMPLATE_VALIDATION_JSON_EXPORT_ACTION_LIST_FAILURE,
  INVALIDATE: types.EXPORT_FORMAT_TRANSFORMATION_TEMPLATE_VALIDATION_JSON_EXPORT_ACTION_LIST_INVALIDATE,
  REMOVE: types.EXPORT_FORMAT_TRANSFORMATION_TEMPLATE_VALIDATION_JSON_EXPORT_ACTION_LIST_REMOVE
})

const templateValidationJSON = combineReducers({
  tradeItemId: createReducer(null, {[types.EXPORT_FORMAT_TRANSFORMATION_TEMPLATE_VALIDATION_JSON_TRADE_ITEM_ID_RECEIVE]: (state, action) => action.tradeItemId || null}),
  exportAction: createReducer(null, {[types.EXPORT_FORMAT_TRANSFORMATION_TEMPLATE_VALIDATION_JSON_EXPORT_ACTION_RECEIVE]: (state, action) => action.exportAction || null}),
  exportActions: templateValidationJSONActions,
  validationResult: createReducer(null, {[types.EXPORT_FORMAT_TRANSFORMATION_TEMPLATE_VALIDATION_JSON_VALIDATION_RESULT_RECEIVE]: (state, action) => action.validationResult || null}),
})

export default combineReducers({
  format,
  formats,
  taxonomies,
  tradeItemCategories,
  businessRules,
  businessRulesets,
  propertyGroups,
  transformationSets,
  tradeItemProperties,
  transformationsProperties,
  excelSheetMappingSelected: createReducer(null, {[types.EXPORT_FORMAT_TRANSFORMATION_EXCEL_SHEET_MAPPING]: (state, action) => action.sheetMapping || null}),
  excelSheetConfigurationSelected: createReducer(null, {[types.EXPORT_FORMAT_TRANSFORMATION_EXCEL_SHEET_CONFIGURATION]: (state, action) => action.sheetConfiguration || null}),
  templateValidationJSON,
})
