import { combineReducers } from "redux"
import createList from "../common/reducers/createList"
import createResource from "../common/reducers/createResource"
import * as types from "./types"
import createReducer from "../common/reducers/createReducer"

const users = createList({
  RESET: types.USER_MANAGEMENT_USERS_LIST_RESET,
  REQUEST: types.USER_MANAGEMENT_USERS_LIST_REQUEST,
  SUCCESS: types.USER_MANAGEMENT_USERS_LIST_SUCCESS,
  FAILURE: types.USER_MANAGEMENT_USERS_LIST_FAILURE,
  INVALIDATE: types.USER_MANAGEMENT_USERS_LIST_INVALIDATE,
  REMOVE: types.USER_MANAGEMENT_USERS_LIST_REMOVE
})

const groups = createList({
  RESET: types.USER_MANAGEMENT_GROUPS_LIST_RESET,
  REQUEST: types.USER_MANAGEMENT_GROUPS_LIST_REQUEST,
  SUCCESS: types.USER_MANAGEMENT_GROUPS_LIST_SUCCESS,
  FAILURE: types.USER_MANAGEMENT_GROUPS_LIST_FAILURE,
  INVALIDATE: types.USER_MANAGEMENT_GROUPS_LIST_INVALIDATE,
  REMOVE: types.USER_MANAGEMENT_GROUPS_LIST_REMOVE
})

const rights = createList({
  RESET: types.USER_MANAGEMENT_RIGHTS_LIST_RESET,
  REQUEST: types.USER_MANAGEMENT_RIGHTS_LIST_REQUEST,
  SUCCESS: types.USER_MANAGEMENT_RIGHTS_LIST_SUCCESS,
  FAILURE: types.USER_MANAGEMENT_RIGHTS_LIST_FAILURE,
  INVALIDATE: types.USER_MANAGEMENT_RIGHTS_LIST_INVALIDATE,
  REMOVE: types.USER_MANAGEMENT_RIGHTS_LIST_REMOVE
})

const manufacturers = createList({
  RESET: types.USER_MANAGEMENT_MANUFACTURERS_LIST_RESET,
  REQUEST: types.USER_MANAGEMENT_MANUFACTURERS_LIST_REQUEST,
  SUCCESS: types.USER_MANAGEMENT_MANUFACTURERS_LIST_SUCCESS,
  FAILURE: types.USER_MANAGEMENT_MANUFACTURERS_LIST_FAILURE,
  INVALIDATE: types.USER_MANAGEMENT_MANUFACTURERS_LIST_INVALIDATE,
  REMOVE: types.USER_MANAGEMENT_MANUFACTURERS_LIST_REMOVE
})

const retailers = createList({
  RESET: types.USER_MANAGEMENT_RETAILERS_LIST_RESET,
  REQUEST: types.USER_MANAGEMENT_RETAILERS_LIST_REQUEST,
  SUCCESS: types.USER_MANAGEMENT_RETAILERS_LIST_SUCCESS,
  FAILURE: types.USER_MANAGEMENT_RETAILERS_LIST_FAILURE,
  INVALIDATE: types.USER_MANAGEMENT_RETAILERS_LIST_INVALIDATE,
  REMOVE: types.USER_MANAGEMENT_RETAILERS_LIST_REMOVE
})

const editedUser = createResource({
  RESET: types.USER_MANAGEMENT_USER_RESET,
  SUCCESS: types.USER_MANAGEMENT_USER_SUCCESS
})

const editedGroup = createResource({
  RESET: types.USER_MANAGEMENT_GROUP_RESET,
  SUCCESS: types.USER_MANAGEMENT_GROUP_SUCCESS
})

const editedRight = createResource({
  RESET: types.USER_MANAGEMENT_RIGHT_RESET,
  SUCCESS: types.USER_MANAGEMENT_RIGHT_SUCCESS
})

const password = createReducer(null, {
  [types.USER_MANAGEMENT_SHOW_USER_PASSWORD]: (s, action) => action.password
})

export default combineReducers({
  users,
  editedUser,
  password,
  groups,
  editedGroup,
  rights,
  editedRight,
  manufacturers,
  retailers,
})
